name: Deploy to dev
on:
  push:
    branches:[ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Redeploy Everything
    steps:
      - run: |
          echo ${{ secrets.DEVSERVERKEY }} &> ~/dev_key
          ssh -i ~/dev_key ubuntu@13.50.238.177
          cd deployment_of_turborepo/ && git pull
          pnpm install
          pnpm run build
          pm2 restart ws-server
          pm2 restart http-server
          pm2 restart web-server
